USE WAREHOUSE ECOM_WH;


DEFINE PROCEDURE DCM_TEST_CASES.test_cases.SP_HEALTHCHECK_PYTHON()
  RETURNS STRING
  LANGUAGE PYTHON
  RUNTIME_VERSION = '3.11'
  HANDLER = 'run'
  EXECUTE AS OWNER
AS
$$
def run(session):
    return 'HEALTHCHECK_OK'
$$;