DEFINE TABLE SELFSERVICE_DB.CORE.FACT_TEST1 (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_DATE DATE,
  AMOUNT NUMBER(18,2),
  CUSTOMER_ID NUMBER
)
COMMENT = 'Fact table test 1';

DEFINE TABLE SELFSERVICE_DB.CORE.FACT_TEST2 (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  EVENT_DATE DATE,
  PRODUCT_ID NUMBER,
  QUANTITY NUMBER
)
COMMENT = 'Fact table test 2';