DEFINE VIEW SELFSERVICE_DB.REPORTING.DIM_TEST1 AS
  SELECT
    CUSTOMER_ID,
    COUNT(*)        AS NB_EVENTS,
    SUM(AMOUNT)     AS TOTAL_AMOUNT
  FROM SELFSERVICE_DB.CORE.FACT_TEST1
  GROUP BY CUSTOMER_ID;

DEFINE VIEW SELFSERVICE_DB.REPORTING.DIM_TEST2 AS
  SELECT
    PRODUCT_ID,
    SUM(QUANTITY)   AS TOTAL_QUANTITY
  FROM SELFSERVICE_DB.CORE.FACT_TEST2
  GROUP BY PRODUCT_ID;