DEFINE DYNAMIC TABLE SELFSERVICE_DB.REPORTING.DYN_SALES_SUMMARY
  TARGET_LAG = '1 hour'
  WAREHOUSE = SELFSERVICE_WH
  AS
  SELECT
    f1.CUSTOMER_ID,
    f1.TOTAL_AMOUNT,
    f2.TOTAL_QUANTITY
  FROM SELFSERVICE_DB.REPORTING.DIM_TEST1 f1
  JOIN SELFSERVICE_DB.REPORTING.DIM_TEST2 f2
    ON f1.CUSTOMER_ID = f2.PRODUCT_ID;