DEFINE ROLE SELFSERVICE_ANALYST
  COMMENT = 'Read-only access to self-service reporting layer';

-- Usage sur les objets infra
DEFINE GRANT USAGE ON WAREHOUSE SELFSERVICE_WH TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT USAGE ON DATABASE SELFSERVICE_DB TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT USAGE ON SCHEMA SELFSERVICE_DB.CORE TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT USAGE ON SCHEMA SELFSERVICE_DB.REPORTING TO ROLE SELFSERVICE_ANALYST;

-- Lecture sur les tables
DEFINE GRANT SELECT ON TABLE SELFSERVICE_DB.CORE.FACT_TEST1 TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT SELECT ON TABLE SELFSERVICE_DB.CORE.FACT_TEST2 TO ROLE SELFSERVICE_ANALYST;

-- Lecture sur les vues et dynamic tables
DEFINE GRANT SELECT ON VIEW SELFSERVICE_DB.REPORTING.DIM_TEST1 TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT SELECT ON VIEW SELFSERVICE_DB.REPORTING.DIM_TEST2 TO ROLE SELFSERVICE_ANALYST;
DEFINE GRANT SELECT ON DYNAMIC TABLE SELFSERVICE_DB.REPORTING.DYN_SALES_SUMMARY TO ROLE SELFSERVICE_ANALYST;