-- =============================================================================
-- USERS : Not managed by DCM Projects
-- =============================================================================
-- DEFINE USER is NOT supported by DCM Projects.
--
-- User creation strategy :
--
--   SERVICE type (service accounts)  → 1 PER ENVIRONMENT
--     Reason: security isolation — separate credentials per env.
--     Ex : SVC_ECOM_LOADER_DEV_CLN / SVC_ECOM_LOADER_DEV / SVC_ECOM_LOADER (PROD)
--
--   PERSON type (human users) → 1 SINGLE SNOWFLAKE ACCOUNT
--     Reason: one person = one login. Multi-env access is managed
--     via role GRANTs (ECOM_ANALYST_DEV_CLN, ECOM_ANALYST_DEV, ECOM_ANALYST).
--
-- Users are created via the pre_scripts/01_create_users.sql script,
-- executed AFTER DCM DEPLOY (warehouses and roles must already exist).
-- The DCM warehouse is used for execution → traceability in QUERY_HISTORY.
-- =============================================================================
